.review-docs:
  stage: docs
  extends:
  - .merge_request_pipelines
  - .no_cache_and_dependencies
  image: ruby:2.6-alpine
  before_script:
  - unset GPG_KEY
  - gem install gitlab --no-doc
  # We need to download the script rather than clone the repo since the
  # review-docs-cleanup job will not be able to run when the branch gets
  # deleted (when merging the MR).
  - apk add --update openssl
<<<<<<< HEAD
  - wget https://gitlab.com/gitlab-org/gitlab-ce/raw/master/scripts/trigger-build-docs
  - chmod 755 trigger-build-docs
=======
  - wget https://gitlab.com/gitlab-org/gitlab/-/raw/master/scripts/trigger-build
  - chmod 755 trigger-build
>>>>>>> v13.5.0
  variables:
    GIT_STRATEGY: none
  when: manual

# Trigger a docs build in gitlab-docs
# Useful to preview the docs changes live
# https://docs.gitlab.com/ee/development/documentation/index.html#previewing-the-changes-live
review-docs-deploy:
  extends:
  - .review-docs
  environment:
    name: review-docs/mr-$CI_MERGE_REQUEST_IID
    # DOCS_REVIEW_APPS_DOMAIN and DOCS_GITLAB_REPO_SUFFIX are secret variables
    # Discussion: https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/14236/diffs#note_40140693
    url: http://docs-preview-$DOCS_GITLAB_REPO_SUFFIX-$CI_MERGE_REQUEST_IID.$DOCS_REVIEW_APPS_DOMAIN/$DOCS_GITLAB_REPO_SUFFIX
    on_stop: review-docs-cleanup
  script:
<<<<<<< HEAD
  - ./trigger-build-docs deploy
=======
  - ./trigger-build docs deploy
>>>>>>> v13.5.0

# Cleanup remote environment of gitlab-docs
review-docs-cleanup:
  extends:
  - .review-docs
  environment:
    name: review-docs/mr-$CI_MERGE_REQUEST_IID
    action: stop
  script:
<<<<<<< HEAD
  - ./trigger-build-docs cleanup
=======
  - ./trigger-build docs cleanup
>>>>>>> v13.5.0
