.binaries: &binaries
  extends:
  - .rules:merge_request_pipelines:no_docs
  - .go-cache
  stage: build
  needs:
  - 'prepare done'
  script:
  - source ci/touch_make_dependencies
  - export platforms=$(echo $CI_JOB_NAME | sed 's|binaries ||')
  - make runner-bin BUILD_PLATFORMS="-osarch='$platforms'"
  artifacts:
    paths:
    - out/binaries/gitlab-runner-*
    exclude:
    - out/binaries/gitlab-runner-helper/
    expire_in: 7d

binaries darwin/amd64: *binaries
binaries freebsd/386 freebsd/amd64 freebsd/arm: *binaries
binaries linux/386 linux/amd64 linux/arm linux/arm64 linux/s390x: *binaries
binaries windows/386 windows/amd64: *binaries
