.coverage_job:
  extends:
  - .merge_request_pipelines
  - .except_docs
  stage: coverage
  when: always

test coverage report:
  extends:
  - .coverage_job
  coverage: /regular total:\s+\(statements\)\s+\d+.\d+\%/
  needs:
  - unit test
  script:
  - source ci/touch_make_dependencies
  - make parallel_test_coverage_report cobertura_report
  artifacts:
    reports:
      cobertura: out/cobertura/cobertura-coverage.xml
    paths:
    - out/coverage/
    expire_in: 7d
    expose_as: 'Code Coverage'

test junit report:
  extends:
  - .coverage_job
  image: $CI_IMAGE
  needs:
  - unit test
  script:
  - source ci/touch_make_dependencies
  - make parallel_test_junit_report
  artifacts:
    reports:
      junit: out/junit/report.xml

race conditions detector:
  extends:
  - .coverage_job
  needs:
  - unit test with race
  script:
  - source ci/touch_make_dependencies
  - make check_race_conditions

code navigation: # See https://docs.gitlab.com/ee/user/project/code_intelligence.html#configuration
  extends:
  - .coverage_job
  allow_failure: true # recommended
  needs:
  - prepare done
  image: sourcegraph/lsif-go:v1
  script:
  - lsif-go
  artifacts:
    reports:
      lsif: dump.lsif

check race unexpected test failures:
  extends:
  - .merge_request_pipelines
  - .except_docs
  stage: coverage
  needs:
  - unit test with race
  script:
  - ./scripts/check_unexpected_test_failures
  when: always

check windows 1809 unexpected test failures:
  extends:
  - .merge_request_pipelines
  - .except_docs
  stage: coverage
  needs:
  - windows 1809 tests
  script:
  - ./scripts/check_unexpected_test_failures
  when: always

.check windows test failures:
  extends:
  - .merge_request_pipelines
  - .except_docs
  stage: coverage
  script:
  - ./scripts/check_windows_failures
  artifacts:
    paths:
    - .test-failures.*.txt.updated
    expire_in: 7d
  when: always

check windows 1809 test failures:
  extends:
  - .check windows test failures
  - .windows1809_variables
  needs:
  - windows 1809 tests

check windows 1903 test failures:
  extends:
  - .check windows test failures
  - .windows1903_variables
  - .runner_master
  needs:
  - windows 1903 tests

check windows 1909 test failures:
  extends:
  - .check windows test failures
  - .windows1909_variables
  - .runner_master
  needs:
  - windows 1909 tests

check windows 2004 test failures:
  extends:
  - .check windows test failures
  - .windows2004_variables
  - .runner_master
  needs:
  - windows 2004 tests
