.image_builder:
  extends:
  - .docker
  stage: prepare
  image: docker:${DOCKER_VERSION}-git
  script:
  - source ./ci/build_ci_image
  only:
    refs:
    - merge_requests@gitlab-org/gitlab-runner

prepare ci image:
  extends:
  - .image_builder
  variables:
    BUILD_IMAGE: $CI_IMAGE
    BUILD_DOCKERFILE: ./dockerfiles/ci/Dockerfile
    GIT_LFS_256_CHECKSUM: 46508eb932c2ec0003a940f179246708d4ddc2fec439dcacbf20ff9e98b957c9
  only:
    changes:
    - dockerfiles/ci/*
    - .gitlab/ci/_common.gitlab-ci.yml
    - .gitlab/ci/prepare.gitlab-ci.yml

prepare alpine-no-root image:
  extends:
  - .image_builder
  variables:
    BUILD_IMAGE: registry.gitlab.com/gitlab-org/gitlab-runner/alpine-no-root:latest
    BUILD_DOCKERFILE: ./tests/dockerfiles/alpine-no-root/Dockerfile
  only:
    changes:
    - tests/dockerfiles/alpine-no-root/*
    - .gitlab/ci/prepare.gitlab-ci.yml
