.image_builder:
  extends:
  - .docker
  stage: prepare
  image: docker:${DOCKER_VERSION}-git
  script:
  - source ./ci/build_ci_image
  only:
    refs:
    - merge_requests@gitlab-org/gitlab-runner

prepare ci image:
  extends:
  - .image_builder
  variables:
    BUILD_IMAGE: $CI_IMAGE
    BUILD_DOCKERFILE: ./dockerfiles/ci/Dockerfile
  only:
    changes:
    - dockerfiles/ci/*
    - .gitlab/ci/prepare.gitlab-ci.yml

prepare alpine-no-root image:
  extends:
  - .image_builder
  variables:
    BUILD_IMAGE: registry.gitlab.com/gitlab-org/gitlab-runner/alpine-no-root:latest
    BUILD_DOCKERFILE: ./tests/dockerfiles/alpine-no-root/Dockerfile
  only:
    changes:
    - tests/dockerfiles/alpine-no-root/*
    - .gitlab/ci/prepare.gitlab-ci.yml
